### ISSUE TITLE
Calculations in Triangle.java are off

### ISSUE THREAD

**Issue by mduffor** [FRC5411/Lofty-2023#21]
Go back and re-do the calculations in Triangle.java
http://www2.clarku.edu/faculty/djoyce/trig/oblique.html (See Law of Cosines)

**Comment by RDc12Programming** [comment]
should be fixed with [this commit](https://github.com/FRC5411/Lofty-2023/commit/85d53806d26e6f119547e9dbd9e7e3c56ab5782c)
